### ISSUE TITLE
Where is the voucher code?

### ISSUE THREAD

**Issue by alanoakden** [amazeeio/DrupalCaresHalfMillionDollarHomepage#16]
Not sure if this is the best place for it. Nevertheless, i donated on Drupal, verified on https://pixelsfordrupal.com/ and now i am not sure where i should see a voucher code?

**Comment by rocketeerbkw** [comment]
I think we're communicating via email, but in case anyone else has this issue. We're operating as a side project so we have to manually process and email voucher codes, they don't get sent immediately after you donate.

If you donated and are still waiting, we haven't process yours yet or we don't have your email, go ahead and open an issue here or send us an email pixelsfordrupal [at] amazee.io

**Comment by chrissnyder2337** [comment]
Thanks for the work you are doing with this side project. I know the only reason I was convinced to donate was to have my face next to those cute doggos. 

Just for the sake of completeness (and to ease your inbox) how long is the average turnaround time? Should people wait 24 hours before reaching out?

Also I would recommend adding this "turnaround time" to the faqs on the site.
